---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker and git on host server/ansible client
    package: name={{ item }} state=present
    loop:
     - docker
     - git
  - name: start docker
    service: name=docker state=started
  - name: get repo
    git: repo=https://github.com/munishdh/devops_project1.git dest=/tmp/gitrepo
  - name: Build Dockerfile
    command: chdir=/tmp/gitrepo docker build -t munishdh/addressbook:ansible .
  - name: run Image
    command: docker run -itd -P munishdh/addressbook:ansible
