---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker and git on host ansible client
    package: name={{ item }} state=present
    loop:
     - docker
     - git
  - name: start docker
    service: name=docker state=started
  - name: clean the destination repo path if exists
    file:
      path: "/tmp/gitrepo"
      state: absent
  - name: clone the repo
    git: repo=https://github.com/munishdh/devops_project1.git dest=/tmp/gitrepo
  - name: Build Dockerfile
    command: chdir=/tmp/gitrepo docker build -t munishdh/addressbook:ansible .
  - name: Login to docker
    command: docker login -u munishdh -p {{ docker_hub_pass }}
  - name: tag the docker image and push the image to dockerhub
    command: docker tag munishdh/addressbook:ansible munishdh/myjenkinsdocker:ansible
  - name: push the image to dockerhub
    command: docker push munishdh/myjenkinsdocker:ansible
