---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker and git on host ansible client
    package: name={{ item }} state=present
    loop:
     - docker
     - git
  - name: start docker
    service: name=docker state=started
  - name: clean the destination repo path if exists
    file:
      path: "/tmp/gitrepo"
      state: absent
  - name: clone the repo
    git: repo=https://github.com/munishdh/devops_project1.git dest=/tmp/gitrepo
  - name: Build and Push Docker image to Dockerhub Registry
      docker_image:
        name: addressbook-war
        build:
          path: /tmp/gitrepo
          pull: true
        state: present
        tag: "latest"
        force_tag: yes
        repository: munishdh/myjenkinsdocker:latest
        push: yes
        source: build
  - name: run Image
    command: docker run -itd -P munishdh/addressbook:ansible
